### ISSUE TITLE
error TS2456: Type alias 'Resolved' circularly references itself.

### ISSUE THREAD

**Issue by parisbrookerPI** [MicrosoftDocs/mslearn-build-api-azure-functions#14]
```
node_modules/@azure/core-tracing/types/core-tracing.d.ts:81:21 - error TS2456: Type alias 'Resolved' circularly references itself.

81 export declare type Resolved<T> = T extends {
                       ~~~~~~~~

node_modules/@azure/core-tracing/types/core-tracing.d.ts:83:41 - error TS2315: Type 'Resolved' is not generic.

83 } ? F extends (value: infer V) => any ? Resolved<V> : never : T;
                                           ~~~~~~~~~~~

node_modules/@azure/core-tracing/types/core-tracing.d.ts:131:212 - error TS2315: Type 'Resolved' is not generic.

131     }, Callback extends (updatedOptions: Options, span: Omit<TracingSpan, "end">) => ReturnType<Callback>>(name: string, operationOptions: Options, callback: Callback, spanOptions?: TracingSpanOptions): Promise<Resolved<ReturnType<Callback>>>; 
```
Following the MS Learn path but getting this when debugging the apis... I might have had a chance with JS, I have 0 TS knowledge

**Comment by mindtd** [comment]
Run into the exact errors as noted - TS2456 once, TS2315 twice. 
![azure_api_run](https://user-images.githubusercontent.com/10556089/185767202-c9c6c967-c1d7-47e4-ab80-ec01fd6a034b.PNG)

**Comment by biofool** [comment]
Resolved requires TS V4 according to https://github.com/Azure/azure-sdk-for-js/issues/21745
" I added typescript 4.6 as a dependency on my module that uses @azure/arm-network. Luckily no breaking changes. Thanks @maorleger !"
However I tried 4.1,4.6 and 4.8 no joy

**Comment by Baso1st** [comment]
It worked for me when I updated the typescript version in my package.json
![image](https://user-images.githubusercontent.com/29257536/189256119-6b1dc6c1-af88-4031-b764-87fe4e5db120.png)

Thanks @biofool

**Comment by biofool** [comment]
open a pull request?

**Comment by magmukendi** [comment]
> It worked for me when I updated the typescript version in my package.json ![image](https://user-images.githubusercontent.com/29257536/189256119-6b1dc6c1-af88-4031-b764-87fe4e5db120.png)
> 
> Thanks @biofool

I had the same issue and this fix (updating the typescript version in the package.json) worked for me as well.

**Comment by ggailey777** [comment]
TypeScript level has been updated. Thanks for the feedback.
