### ISSUE TITLE
'Cannot find module '@azure/identity' Require stack:

### ISSUE THREAD

**Issue by Baso1st** [MicrosoftDocs/mslearn-build-api-azure-functions#16]
Worker was unable to load function CreateProduct: 'Cannot find module '@azure/identity' Require stack:
<Your directory>\mslearn-build-api-azure-functions\api\node_modules\@azure\cosmos\dist\index.js........

A **workaround** to it according to https://github.com/Azure/azure-sdk-for-js/issues/22968#issue-1345800240
is to **downgrade the @azure/cosmos version.**

![image](https://user-images.githubusercontent.com/29257536/189360592-d00973a2-324f-4867-90b2-e9d0068541fd.png)

Now it should work just fine for you. If it didn't try deleting the **package-lock.json** file and also delete the **node_modules** folder then run it again.

**Comment by ggailey777** [comment]
Thanks @Baso1st we are keeping the Cosmos DB at 3.9.3 for this project
